server:
  port: 8082

spring:
  application:
    name: MOVIE-SERVICE
    
  datasource:
    url: jdbc:hsqldb:hsql://localhost/xdb
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: SA
    password: 
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    